steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"

- id: 'run deployment script'
  name: 'alpine'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      echo "*************** Run Deployment Script ******************"
      deploy.sh
  env:
  - 'AUTH_OPTION=Skip'
